project_id = "nvnnzovquizugwyrlkpw"

[functions.fetch-product-images]
verify_jwt = false

[functions.generate-product-image]
verify_jwt = false

[functions.migrate-product-images]
verify_jwt = false

[functions.clear-product-images]
verify_jwt = false

